Update README.md
To fix the missing header file:

device_monitor.c:338:10: fatal error: libudev.h: File or directory not found
 #include <libudev.h>